export const convertHotelPrices = ({
  hotels,
  rate,
  currency,
}) => {

  return hotels.map((hotel) => {

    return {

      ...hotel,

      originalPrice: hotel.price,

      originalTax: hotel.tax,

      price: Number(
        (hotel.price * rate).toFixed(2)
      ),

      tax: Number(
        (hotel.tax * rate).toFixed(2)
      ),

      currency,
    };
  });
};

// export const currencySymbols = {
//   AED: "د.إ",
//   AFN: "؋",
//   ALL: "L",
//   AMD: "֏",
//   ANG: "ƒ",
//   AOA: "Kz",
//   ARS: "$",
//   AUD: "A$",
//   AWG: "ƒ",
//   AZN: "₼",
//   BAM: "KM",
//   BBD: "$",
//   BDT: "৳",
//   BGN: "лв",
//   BHD: ".د.ب",
//   BIF: "FBu",
//   BMD: "$",
//   BND: "$",
//   BOB: "Bs.",
//   BRL: "R$",
//   BSD: "$",
//   BTN: "Nu.",
//   BWP: "P",
//   BYN: "Br",
//   BZD: "BZ$",
//   CAD: "C$",
//   CDF: "FC",
//   CHF: "CHF",
//   CLF: "UF",
//   CLP: "$",
//   CNH: "¥",
//   CNY: "¥",
//   COP: "$",
//   CRC: "₡",
//   CUP: "$",
//   CVE: "$",
//   CZK: "Kč",
//   DJF: "Fdj",
//   DKK: "kr",
//   DOP: "RD$",
//   DZD: "دج",
//   EGP: "£",
//   ERN: "Nfk",
//   ETB: "Br",
//   EUR: "€",
//   FJD: "$",
//   FKP: "£",
//   FOK: "kr",
//   GBP: "£",
//   GEL: "₾",
//   GGP: "£",
//   GHS: "₵",
//   GIP: "£",
//   GMD: "D",
//   GNF: "FG",
//   GTQ: "Q",
//   GYD: "$",
//   HKD: "HK$",
//   HNL: "L",
//   HRK: "kn",
//   HTG: "G",
//   HUF: "Ft",
//   IDR: "Rp",
//   ILS: "₪",
//   IMP: "£",
//   INR: "₹",
//   IQD: "ع.د",
//   IRR: "﷼",
//   ISK: "kr",
//   JEP: "£",
//   JMD: "J$",
//   JOD: "JD",
//   JPY: "¥",
//   KES: "KSh",
//   KGS: "с",
//   KHR: "៛",
//   KID: "$",
//   KMF: "CF",
//   KRW: "₩",
//   KWD: "KD",
//   KYD: "$",
//   KZT: "₸",
//   LAK: "₭",
//   LBP: "ل.ل",
//   LKR: "Rs",
//   LRD: "$",
//   LSL: "L",
//   LYD: "LD",
//   MAD: "د.م.",
//   MDL: "L",
//   MGA: "Ar",
//   MKD: "ден",
//   MMK: "Ks",
//   MNT: "₮",
//   MOP: "MOP$",
//   MRU: "UM",
//   MUR: "₨",
//   MVR: "Rf",
//   MWK: "MK",
//   MXN: "$",
//   MYR: "RM",
//   MZN: "MT",
//   NAD: "$",
//   NGN: "₦",
//   NIO: "C$",
//   NOK: "kr",
//   NPR: "₨",
//   NZD: "NZ$",
//   OMR: "﷼",
//   PAB: "B/.",
//   PEN: "S/",
//   PGK: "K",
//   PHP: "₱",
//   PKR: "₨",
//   PLN: "zł",
//   PYG: "₲",
//   QAR: "﷼",
//   RON: "lei",
//   RSD: "дин.",
//   RUB: "₽",
//   RWF: "RF",
//   SAR: "﷼",
//   SBD: "$",
//   SCR: "₨",
//   SDG: "SDG",
//   SEK: "kr",
//   SGD: "S$",
//   SHP: "£",
//   SLE: "Le",
//   SLL: "Le",
//   SOS: "Sh",
//   SRD: "$",
//   SSP: "£",
//   STN: "Db",
//   SYP: "£",
//   SZL: "E",
//   THB: "฿",
//   TJS: "ЅМ",
//   TMT: "m",
//   TND: "د.ت",
//   TOP: "T$",
//   TRY: "₺",
//   TTD: "TT$",
//   TVD: "$",
//   TWD: "NT$",
//   TZS: "Sh",
//   UAH: "₴",
//   UGX: "USh",
//   USD: "$",
//   UYU: "$U",
//   UZS: "so'm",
//   VES: "Bs.",
//   VND: "₫",
//   VUV: "VT",
//   WST: "WS$",
//   XAF: "FCFA",
//   XCD: "EC$",
//   XCG: "CG$",
//   XDR: "SDR",
//   XOF: "CFA",
//   XPF: "₣",
//   YER: "﷼",
//   ZAR: "R",
//   ZMW: "ZK",
//   ZWG: "ZiG",
//   ZWL: "Z$"
// };

export const getCurrencySymbol = (currencyCode) => {
  try {
    const parts = new Intl.NumberFormat("en", {
      style: "currency",
      currency: currencyCode,
    }).formatToParts(1);

    return (
      parts.find((p) => p.type === "currency")?.value ||
      currencyCode
    );
  } catch {
    return currencyCode;
  }
};