export const DESTINATIONS = {
  beach: [
    { id: "360542", name: "Goa", City: "Goa, India (GOX-New Goa Intl.)" },
    {
      id: "358095",
      name: "Bali",
      City: "Balikpapan, East Kalimantan, Indonesia",
    },
    { id: "228284", name: "Maldives", City: "Malé, Kaafu Atoll, Maldives" },
    {
      id: "247214",
      name: "Phuket",
      City: "Phuket, Thailand (HKT-Phuket Intl.)",
    },
    { id: "221688", name: "Dubai", City: "Dubai, Dubai, United Arab Emirates" },
  ],

  mountain: [
    { id: "334045", name: "Manali", City: "Manali, Himachal Pradesh, India" },
    { id: "246679", name: "Shimla", City: "Shimla, Himachal Pradesh, India" },
    {
      id: "333479",
      name: "Kashmir",
      City: "Pahalgam, Jammu and Kashmir, India",
    },
    {
      id: "64490",
      name: "Switzerland",
      City: "Swiss, West Virginia, United States of America",
    },
    { id: "227728", name: "Leh Ladakh", City: "Leh, Ladakh, India" },
  ],

  luxury: [
    { id: "437227", name: "Paris", City: "Paris, France" },
    { id: "480416", name: "Rome", City: "Rome, Lazio, Italy" },
    { id: "246673", name: "Singapore", City: "Singapore, Singapore" },
    { id: "221688", name: "Dubai", City: "Dubai, Dubai, United Arab Emirates" },
  ],

  weekend: [
    { id: "227736", name: "Jaipur", City: "Jaipur, Rajasthan, India" },
    { id: "246754", name: "Udaipur", City: "Udaipur, Rajasthan, India" },
    { id: "333732", name: "Lonavala", City: "onavala, Maharashtra, India" },
    { id: "329199", name: "Rishikesh", City: "Rishikesh, Uttarakhand, India" },
  ],
  Toprated: [
    {
      id: "9917325614",
      name: "Taj Lake Palace, Udaipur, Rajasthan, IN",
      City: "Udaipur, India",
      image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa",
      desc: "Luxury lakefront palace hotel with royal interiors, fine dining, and breathtaking sunset views across Udaipur.",
      rating: 4.9,
    },
    {
      id: "9939616193",
      name: "Rambagh Palace, Jaipur, Rajasthan, IN",
      City: "Jaipur, India",
      image: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
      desc: "Historic royal residence offering premium suites, peaceful gardens, and traditional Rajasthani hospitality experience.",
      rating: 4.8,
    },
    {
      id: "9937732294",
      name: "Umaid Bhawan Palace, Jodhpur, Rajasthan, IN",
      City: "Jodhpur, India",
      image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
      desc: "Grand heritage palace featuring luxurious rooms, city skyline views, and exceptional personalized guest services.",
      rating: 5,
    },
    {
      id: "9941215486",
      name: "The Taj Mahal Palace Mumbai, Mumbai, Maharashtra, IN",
      City: "Mumbai, India",
      image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
      desc: "Iconic waterfront hotel blending timeless architecture, elegant rooms, and world-class dining experiences beautifully.",
      rating: 4.7,
    },
    {
      id: "9939646293",
      name: "The Oberoi Udaivilas, Udaipur, Udaipur, Rajasthan, IN",
      City: "Udaipur, India",
      image: "https://images.unsplash.com/photo-1484154218962-a197022b5858",
      desc: "Magnificent luxury resort surrounded by lakes, fountains, and beautifully designed traditional palace-style architecture.",
      rating: 4.9,
    },
    {
      id: "9939680193",
      name: "The Oberoi Amarvilas, Agra, Agra, Uttar Pradesh, IN",
      City: "Agra, India",
      image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
      desc: "Elegant property offering stunning Taj Mahal views, premium suites, and unforgettable luxury hospitality experiences.",
      rating: 4.8,
    },
    {
      id: "9939671686",
      name: "The Leela Palace Udaipur, Udaipur, Rajasthan, IN",
      City: "Udaipur, India",
      image: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c",
      desc: "Beautiful lakeside palace hotel with spacious suites, rooftop dining, and relaxing spa wellness treatments.",
      rating: 4.6,
    },
    {
      id: "9939634113",
      name:"The Leela Palace New Delhi, New Delhi, Delhi, IN",
      City: "New Delhi, India",
      image: "https://images.unsplash.com/photo-1455587734955-081b22074882",
      desc: "Modern luxury hotel featuring sophisticated interiors, premium restaurants, and exceptional city-center convenience for travelers.",
      rating: 4.7,
    },
    {
      id: "9939590520",
      name: "Taj Falaknuma Palace, Hyderabad, Telangana, IN",
      City: "Hyderabad, India",
      image: "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a",
      desc: "Royal hilltop palace offering vintage elegance, luxurious suites, and unforgettable heritage-inspired hospitality experiences.",
      rating: 5,
    },
    {
      id: "9930956191",
      name: "SUJÁN JAWAI - Relais & Chateaux, Pāli, Rajasthan, IN",
      City: "Rajasthan, India",
      image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
      desc: "Luxury wilderness retreat surrounded by nature, wildlife safaris, and peaceful mountain landscape experiences daily.",
      rating: 4.8,
    },
    {
      id: "9915263861",
      name: "Chandys Windy Woods, Munnar, Kerala, IN",
      City: "Munnar, Kerala, India",
      image: "https://images.unsplash.com/photo-1468824357306-a439d58ccb1c",
      desc: "Scenic mountain resort featuring misty valley views, cozy rooms, and refreshing natural surroundings throughout.",
      rating: 4.5,
    },
    {
      id: "9939642475",
      name:"Blanket Hotel & Spa, Munnar, Kerala, IN",
      City: "Munnar, India",
      image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
      desc: "Peaceful hilltop retreat with waterfall views, luxurious spa treatments, and spacious premium accommodation options.",
      rating: 4.6,
    },
    {
      id: "9939761186",
      name: "The Lodhi, New Delhi, Delhi, IN",
      City: "New Delhi, India",
      image: "https://images.unsplash.com/photo-1505692952047-1a78307da8f2",
      desc: "Contemporary luxury hotel known for stylish suites, private plunge pools, and exceptional personalized guest services.",
      rating: 4.7,
    },
    {
      id: "9930857974",
      name: "The Imperials, Boursault, Grand Est, FR",
      City: "Boursault, FR",
      image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
      desc: "Classic heritage hotel offering elegant architecture, luxury accommodations, and premium fine dining experiences for travelers.",
      rating: 4.8,
    },
    {
      id: "742456",
      name: "Rääsa, Ida-Viru County, Estonia",
      City: "Lüganuse Parish",
      image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791",
      desc: "Boutique heritage hotel near Mehrangarh Fort featuring stylish rooms and breathtaking rooftop dining atmosphere nightly.",
      rating: 4.6,
    },
    {
      id: "360313",
      name: "Ritz Carlton Beach, Koh Samui, Surat Thani Province, Thailandn",
      City: "Surat Thani Province",
      image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
      desc: "Premium urban luxury hotel with modern interiors, rooftop lounges, and outstanding hospitality services for guests.",
      rating: 4.9,
    },
    {
      id: "9939518957",
      name: "ITC Grand Chola, a Luxury Collection Hotel, Chennai, Chennai, Tamil Nadu, IN",
      City: "Chennai, India",
      image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
      desc: "Massive luxury property inspired by royal architecture, offering elegant rooms and premium culinary experiences daily.",
      rating: 4.7,
    },
    {
      id: "9939628485",
      name: "The Westin Resort Guam, Tamuning, Tamuning, GU",
      City: "Tamuning",
      image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
      desc: "Beachside luxury resort with relaxing ambiance, infinity pools, and modern ocean-view accommodations for visitors.",
      rating: 4.5,
    },
    {
      id: "561199",
      name: "Hyatt Regency Aruba Resort and Casino, Noord, Aruba Island, AW",
      City: "Aruba Island",
      image: "https://images.unsplash.com/photo-1484154218962-a197022b5858",
      desc: "Elegant city hotel featuring spacious suites, wellness facilities, and premium dining options for comfortable stays.",
      rating: 4.4,
    },
    {
      id: "9970984416",
      name: "Housr Ferguson Apartments Marathahalli Near Radisson Blu Hotel, Bangalore, Karnataka, IN",
      City: "Karnataka",
      image: "https://images.unsplash.com/photo-1472220625704-91e1462799b2",
      desc: "Modern luxury hotel close to major attractions, offering stylish rooms and exceptional guest hospitality services.",
      rating: 4.6,
    },
  ],
};
